name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # Needed to create releases and upload assets

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create release archives
        run: |
          mkdir -p dist
          VERSION=${GITHUB_REF##*/}
          zip -r "dist/pdf_to_md-${VERSION}.zip" . -x "*.git*" "venv/*"
          tar --warning=no-file-changed --exclude='.git*' --exclude='venv'               -czf "dist/pdf_to_md-${VERSION}.tar.gz" .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: |
            dist/pdf_to_md-${{ github.ref_name }}.zip
            dist/pdf_to_md-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
